name: Generate Stats

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours, on the hour (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Update contribution snake
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk/svg@v3
        with:
          github_user_name: trixxmanaty
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
